<?php
/******************************************
INDONESIAN
Admin Category Language
******************************************/

$lang['categories'] = 'Kategori-kategori';
$lang['error_must_select'] = 'Anda harus memilih kategori untuk diatur';
$lang['error_not_found'] = 'Kategori yang diminta tidak ditemukan.';
$lang['organize_category'] = 'Pengaturan Kategori "%s"';
$lang['organize'] = 'Pengaturan';
$lang['category_id'] = 'ID';
$lang['category_form'] = 'Form Kategori';
$lang['name'] = 'Nama';
$lang['slug'] = 'Slug';
$lang['hidden'] = 'Sembunyikan';
$lang['description'] = 'Deskripsi';
$lang['excerpt'] = 'Kutipan';
$lang['image'] = 'Gambar';
$lang['sequence'] = 'Urutan';
$lang['seo_title'] = 'Judul untuk SEO';
$lang['meta'] = 'Meta Data';
$lang['message_category_saved'] = 'Kategori telah disimpan!';
$lang['error_file_upload'] = '<p>Anda tidak memilih file untuk diupload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category'] = 'Kategori berhasil dihapus.';
$lang['current_file'] = 'File Saat Ini';
$lang['confirm_delete_category'] = 'Anda yakin akan menghapus kategori ini?';
$lang['add_new_category'] = 'Tambah Kategori Baru';
$lang['top_level_category'] = 'Level teratas Kategori';
$lang['no_categories'] = 'Saat ini belum ada kategory';
$lang['attributes'] = 'Attribute';
$lang['seo'] = 'SEO';
$lang['parent'] = 'Induk';
$lang['meta_data_description'] = 'ex. &lt;meta name="description" content="Kami menjual produk yang Anda butuhkan" /&gt;';
$lang['drag_and_drop'] = 'Drag dan drop produk jika Anda ingin memunculkannya.';
$lang['sku'] = 'SKU';
$lang['price'] = 'Harga';
$lang['sale'] = 'Diskon';
$lang['max_file_size'] = 'Ukuran File Maksimal';
$lang['sort_name_asc'] = 'Nama (A - Z)';
$lang['sort_name_desc'] = 'Nama (Z - A)';
$lang['sort_price_asc'] = 'Harga Rendah - Tinggi';
$lang['sort_price_desc'] = 'Harga Tinggi - Rendah';
$lang['sort'] = 'Urutkan';
